version: '2'

services:
  cats:
    build:
      context: .
      dockerfile: Dockerfile.debug
    privileged: true
    ports: ["9091:9091"]
    volumes: 
      - .:/cats
    environment:
      DEBUG: 'true'
  